color: null
fieldLayouts:
  c5dec896-8476-4ba0-8062-c50fa4321660:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-06T14:09:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7955e7d1-6cd4-427b-b182-52ed67a8b638
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-06T18:25:55+00:00'
            elementCondition: null
            fieldUid: 8f9f9e63-916f-4e0b-a13f-237eaedf6d60 # Dropdown
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27a82eee-9f74-4dc9-8355-c1b5347cf121
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 670eff7d-b097-4aaa-a4f7-7be272675cfa
        userCondition: null
handle: aboutMe
hasTitleField: true
icon: person
name: 'About Me'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
