color: null
fieldLayouts:
  0bcf0614-0dcd-4aae-9150-093e91c44623:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-08T01:34:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7059eaaa-cbda-423c-aad6-0be46792e485
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-08T01:38:19+00:00'
            elementCondition: null
            fieldUid: f5f813f1-a303-421c-bb18-6dfaf36fa7b5 # Image
            handle: resume
            includeInCards: false
            instructions: null
            label: 'Resume Override'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c733d83-875b-4298-9cb1-032cb094fc38
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-08T01:38:19+00:00'
            elementCondition: null
            fieldUid: 057dd961-93b0-4b3c-8bdc-29f1a26a6c38 # Rich Text
            handle: coverLetter
            includeInCards: false
            instructions: null
            label: 'Cover Letter'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6ade623-8e76-4758-a4bd-579c1ea77e01
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-08T01:38:19+00:00'
            elementCondition: null
            fieldUid: 69a0b0da-4944-4393-b673-5c6ccd3b2480 # Domain
            handle: jobListingUrl
            includeInCards: false
            instructions: null
            label: 'Job Listing URL'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f9a163f-e237-45f2-90b2-5e99db2c8234
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-08T14:48:44+00:00'
            elementCondition: null
            fieldUid: f23dd440-00b7-4eba-82b4-705eecd516ff # CoverLetterField
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 971c4d5e-af9f-4e48-8710-fa4f5e47a183
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 346ec8cd-d770-4f7f-a264-3f57725de9e4
        userCondition: null
handle: application
hasTitleField: true
icon: null
name: Application
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
