color: null
fieldLayouts:
  f357c0bd-f027-4eaa-868e-256b14c85542:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-16T00:08:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e078f39b-d460-49c9-8cfc-161438833ce5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-16T00:10:27+00:00'
            elementCondition: null
            fieldUid: cc4f624e-61f6-4994-928d-51df13c898c4 # Text Field
            handle: description
            includeInCards: false
            instructions: null
            label: Description
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22ac9ebd-bcf9-4dd3-847f-88f95be7bc83
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f0512c28-186b-493e-984f-1fbd0e9de52b
        userCondition: null
handle: banner
hasTitleField: true
icon: null
name: Banner
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
