color: null
fieldLayouts:
  654ee4e9-1a69-4a8a-aac0-8fcf12bdfe90:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-06T14:08:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0385efb0-06f5-4349-8444-f6f7a8d664dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-06T18:56:38+00:00'
            elementCondition: null
            fieldUid: 69a0b0da-4944-4393-b673-5c6ccd3b2480 # Domain
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c1175fe-145e-4a2c-8c42-2c2cc1a9e6dc
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-12T00:50:44+00:00'
            elementCondition: null
            fieldUid: 1dff345e-edd5-4f00-94d7-b6190c109b2a # Asset
            handle: logo
            includeInCards: false
            instructions: null
            label: Logo
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0327ba91-5e4a-4bc4-8d89-b0c6cfd38e20
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-11T04:40:16+00:00'
            elementCondition: null
            fieldUid: f54dead2-8c9d-44f7-8eec-cdf5f89fd0f3 # Skills and Technologies
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03773896-fed3-48d6-b9a3-3f82e572fbb1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-12T02:12:23+00:00'
            elementCondition: null
            fieldUid: 057dd961-93b0-4b3c-8bdc-29f1a26a6c38 # Rich Text
            handle: projectBackground
            includeInCards: false
            instructions: null
            label: 'Project Background'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd344446-dfa1-4ed6-ac85-6ee497cdb53d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-06T18:26:27+00:00'
            elementCondition: null
            fieldUid: 057dd961-93b0-4b3c-8bdc-29f1a26a6c38 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 552e265a-7104-40fa-8512-dab199a356c0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-12T00:33:38+00:00'
            elementCondition: null
            fieldUid: 1dff345e-edd5-4f00-94d7-b6190c109b2a # Asset
            handle: previewImage
            includeInCards: false
            instructions: null
            label: 'Preview Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8261521d-dc22-4d78-aa4d-8cc8dbbe9c75
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 24e66900-2680-4c3e-8e3e-e6e7263574d7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-12T01:43:06+00:00'
            elementCondition: null
            fieldUid: 8eb826e2-71f2-4e31-a635-bbbec0160110 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58b2c674-863f-48b1-b1bd-22da58ca9c25
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-06T18:56:38+00:00'
            elementCondition: null
            fieldUid: 8eb826e2-71f2-4e31-a635-bbbec0160110 # Headline
            handle: excerpt
            includeInCards: false
            instructions: null
            label: Excerpt
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abda8ff4-ff53-4f38-a7bc-a9f91242ceef
            userCondition: null
            warning: null
            width: 100
        name: Card
        uid: 240ea656-a68f-48be-8d86-4b09fe23f361
        userCondition: null
handle: sites
hasTitleField: true
icon: browser
name: Sites
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
