baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: hirejeffrey.com
primary: true
siteGroup: 40685d18-1de1-4e3a-9d7a-f4545dbb88fb # hirejeffrey.com
sortOrder: 1
