altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  5a598b61-8f67-43f0-89bb-867e612cd597:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-07T20:29:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 375df8a1-4418-4816-96bf-3824ff3d90d8
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-02-12T15:37:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 09afa82c-5ce8-4290-8800-da85534e30c4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-12T15:37:42+00:00'
            elementCondition: null
            fieldUid: 69a0b0da-4944-4393-b673-5c6ccd3b2480 # Domain
            handle: null
            includeInCards: false
            instructions: null
            label: 'Domain (optional)'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce9e88ba-8bc0-4627-8768-458935e47bec
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 500267a8-cb2f-406b-a214-d2af652e7b5e
        userCondition: null
fs: s3
handle: aws
name: AWS
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
