columnSuffix: null
handle: coverletterfield
instructions: null
name: CoverLetterField
searchable: false
translationKeyFormat: null
translationMethod: none
type: jeffreybenusa\crafthirejeffreychat\fields\CoverLetter
