columnSuffix: null
handle: index
instructions: 'SEO Index toggle'
name: Index
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
