columnSuffix: null
handle: matrix
instructions: null
name: Matrix
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - f97878e5-5b0c-4591-9251-1e45cbefc029 # Page
    -
      __assoc__:
        -
          - uid
          - 8a8463fa-1a16-4043-b029-a2119901c8ad # Banner
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
