columnSuffix: null
handle: richText
instructions: null
name: 'Rich Text'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 99dfbf8d-7e14-44f7-a26a-20d25e1ef691 # Simple
  createButtonLabel: null
  defaultTransform: a0b88a09-1f4d-443e-aeaf-7c47ceb3f466 # Content Image
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
