defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: 7e6c4bad-2006-4019-96e6-249dcec6cd7e # Application
handle: applications
maxAuthors: 1
name: Applications
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  7b44d990-5db1-4fac-be77-aee6b2337323: # hirejeffrey.com
    enabledByDefault: true
    hasUrls: true
    template: applications/_entry.twig
    uriFormat: 'applications/{slug}'
type: channel
