defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c6a1af4c-b79e-4c38-9470-56d95ceadd16 # Quotes
handle: quotes
maxAuthors: 1
name: Quotes
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7b44d990-5db1-4fac-be77-aee6b2337323: # hirejeffrey.com
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
