defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9a4f0ca1-ced8-4a29-8f8a-dba746be2d4f # Resume
handle: resume
maxAuthors: 1
name: Resume
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7b44d990-5db1-4fac-be77-aee6b2337323: # hirejeffrey.com
    enabledByDefault: true
    hasUrls: true
    template: resume/_index.twig
    uriFormat: resume
type: single
