tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-02-15T16:38:21-08:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: e69a474a-d01a-43db-9169-c8d1ccbbc244
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: '2025-02-15T16:38:21-08:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: f73edac3-3ee0-472a-a8e6-cd1d73567e73
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-02-15T16:38:21-08:00'
        elementCondition: null
        includeInCards: true
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: a050a75a-fa0e-4a74-bf60-5ffba8c9f4f2
        userCondition: null
        warning: null
    name: Content
    uid: a1a72eea-c7b2-4724-83a6-c240e6743ff6
    userCondition: null
